name: seed

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: Ensure branch
        run: (git checkout -b trigger-job-01  || true ) && git pull -f origin trigger-job-01 && git pull -f origin master
        if: always()
      - name: Regen readme
        run: echo -e "$(sed '$ d' README.md )\n00 $(date -u +'%Y-%m-%dT%H:%M:%SZ') ${GITHUB_SHA}" > README.md
        if: always()
      - name: Trigger job 01
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Trigger job 01
          branch: trigger-job-01
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

