name: acr

on:
  push:
    branches:
      - trigger-job-01

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: run tests against ACR
        run: ci/ci-acr.sh
        env:
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      - name: Ensure branch
        run: (git checkout -b trigger-job-02  || true ) && git pull -f origin trigger-job-02 && git pull -f origin trigger-job-01
        if: always()
      - name: Regen readme
        run: echo -e "$(sed '$ d' README.md )\n01 $(date -u +'%Y-%m-%dT%H:%M:%SZ') ${GITHUB_SHA}" > README.md
        if: always()
      - name: Trigger job 02
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Trigger job 02
          branch: trigger-job-02
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
