name: dockerhub

on:
  push:
    branches:
      - trigger-job-03

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: run tests against Docker Hub
        run: ci/ci-dockerhub.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Ensure branch
        run: (git checkout -b trigger-job-04  && git pull -f origin trigger-job-03 ) || true
        if: always()
      - name: Regen readme
        run: echo -e "$(sed '$ d' README.md )\n03 $(date -u +'%Y-%m-%dT%H:%M:%SZ') ${GITHUB_SHA}" > README.md
        if: always()
      - name: Trigger job 04
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Trigger job 04
          branch: trigger-job-04
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
