name: zot-auth

on:
  push:
    branches:
      - deploy-github-pages

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      - name: Ensure branch
        run: (git checkout -b master || true ) && git pull -f origin master && git pull -f deploy-github-pages
        if: always()
      - name: Regen readme
        run: echo -e "$(sed '$ d' README.md )\n99-deploy-pages $(date -u +'%Y-%m-%dT%H:%M:%SZ') ${GITHUB_SHA}" > README.md
        if: always()
      - name: Deploy GitHub Pages site
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Deploy GitHub Pages site
          branch: master
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()